name: Android CI

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: bump version code
        run: ./.github/scripts/bumpVersion.sh

      - name: commit version changes
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'Version CI'
          git config --global user.email 'chamilton0@users.noreply.github.com'
          git commit -am "ci(version): updates version"
          git push --force

  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Version
        id: version
        working-directory: ./
        run: |
          version=$(grep -oP '\"version\": \s*"\K[^"\047]+' package.json | head -n 1)
          echo "Extracted version: $version"
          echo "release_version=$version" >> $GITHUB_OUTPUT

      - name: Build image
        run: | 
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')
          docker build . --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        if: github.ref == 'refs/heads/master'
        run: |
          IMAGE_ID=ghcr.io/$IMAGE_NAME

          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=${{ steps.version.outputs.release_version }}
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Tag commit
        if: github.ref == 'refs/heads/master'
        run: |
          tag=v${{ steps.version.outputs.release_version }}
          message=${{ steps.version.outputs.release_version }}
          git config --global user.name 'Version CI'
          git config --global user.email 'chamilton0@users.noreply.github.com'
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
